spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GoodOrBad?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Hada01!!!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  server:
    servlet:
      session:
        timeout: 1h


